### ISSUE TITLE
When "full disk encryption" is enabled, no partition is mounted on /cdrom during OOBE.

### ISSUE THREAD

**Issue by lihow731** [dell/dell-recovery#105]
In normal installation, the recovery partition will be mounted on /cdrom during OOBE.
But,  when FDE is enabled, no partition is mounted on /cdrom during OOBE.

**Comment by superm1** [comment]
That's correct if you use fde that no recovery partition is created. This is a limitation based on how it works. Actually Dell recovery is not installed into target system when you have enabled fde.

**Comment by superm1** [comment]
Just to clarify; if you choose the option to let you pick the partitioning layout no recovery partition is created.  It is all Ubuntu installer at that point.

If using https://github.com/dell/dell-recovery/pull/92 then recovery partitions would be created.

**Comment by alex-tu-cc** [comment]
but we still need /cdrom during the OOBE phase.
Because of several cases:
1. From Focal, we move most of packages to /cdrom/debs to gain the ability of rolling security update after base image released.
2. For cases like RED or Factory security update we did in bionic, some packages in /cdrom/debs are needed during OOBE

**Comment by superm1** [comment]
Moving packages to /cdrom/debs shouldn't actually prevent any installation during phase 2 though.  Can you please confirm exactly which packages get installed during OOBE phase in a "regular" situation?  I would expect it's only language packs, which is a definite limitation from this approach.

Also in bionic case, please review that too?

It really isn't possible to have both FDE from the Ubuntu installer when also having a recovery partition without major changes to installation process. 

Some of this was proposed in the FDE PR (https://github.com/dell/dell-recovery/pull/92) which would allow using both, but even that requires some installer changes.

So in _general_ we should try to go towards needing to install everything possible in phase 2.  

Another solution that can be _considered_ is to mount USB key during OOBE in FDE scenario, but that also may be a little complex because USB key should be "ejected" at end of phase 2 and normally it needs to be re-plugged to reset.

**Comment by alex-tu-cc** [comment]
> I would expect it's only language packs, which is a definite limitation from this approach.
Yes, this is the problem, because some security update introduced new version of language packs.
So, the new language packs are expected to be installed after user selected language in OOBE.

> Another solution that can be considered is to mount USB key during OOBE in FDE scenario, but that also may be a little complex because USB key should be "ejected" at end of phase 2 and normally it needs to be re-plugged to reset.
So far, this seems to be the only workaround for the current FDE implementation.

**Comment by superm1** [comment]
>So, the new language packs are expected to be installed after user selected language in OOBE.

With FDE enabled there shouldn't be languages listed in OOBE.  It should be English only (since those language packs weren't available during OOBE).

>So far, this seems to be the only workaround for the current FDE implementation.

Can you perform an experiment to confirm if the ejected USB key behavior I described is what happens?

1. Run full install with FDE, but leave USB key plugged in all the way to end of OOBE.
2. After OOBE, see if you can access filesystem on the key from desktop.  

If you can't, then we'll need to modify casper behavior to not "eject" the key for this idea to work.

If you can, then this would be my proposal to explore that possibility:
1. Modify this code so that dell-recovery package stays installed even with FDE enabled.
https://github.com/dell/dell-recovery/blob/384345a64e4c4fd814121773a368809a61a03d38/Dell/recovery_common.py#L719
2. Modify https://github.com/dell/dell-recovery/blob/master/late/scripts/oem_config.sh to allow finding the USB key while plugged in if no recovery partition is on the disk.

**Comment by fourdollars** [comment]
My idea is to copy all files from USB or DVD into /cdrom on the target root filesystem when it detects no recovery partition installation.
Find some way to use that /cdrom during the OOBE and remove it completely after the OOBE.
How do you think about this idea?

**Comment by superm1** [comment]
>How do you think about this idea?

My real preference would be that we could still have a recovery partition even with FDE enabled, but I'm aware that preseeding isn't really built for that right now.

>My idea is to copy all files from USB or DVD into /cdrom on the target root filesystem when it detects no recovery partition installation.

So for now that's not a bad idea.  It would certainly keep everything relatively clean implementation wise and remove the dependency on USB key staying plugged in during OOBE.

I think you don't need to clone all files from `/cdrom`.  Can focus specifically on `pool` and `debs` directories.  This should improve performance as you don't actually copy over the large squashfs in `casper/

>Find some way to use that /cdrom during the OOBE and remove it completely after the OOBE.

I think this copy routine could run during `Install` of `dell-bootstrap` ubiquity plugin when no recovery partition detected.

Extra code can be added into the `oem config.sh` for detecting this scenario both for setting up the pool and for late cleanup.

**Comment by fourdollars** [comment]
I come out some different idea during my investigation today.
Is it OK to install all language packs when it detects no recovery installation and then remove other language packs after OOBE?

**Comment by superm1** [comment]
I would expect this would make oobe very time consuming for for that scenario, no?

**Comment by fourdollars** [comment]
If we copy debs/dists/pool into /target and then remove them after OOBE, that will also be very time consuming.
I don't know which one is more very time consuming so far.

**Comment by superm1** [comment]
I have another thought.  What if when custom partitioning is selected in dell-recovery undo the preseed for language.  This should make language get selected in ubiquity during installer.  This would let user pick the language and no need to copy all language packs or install all language packs.

**Comment by fourdollars** [comment]
@superm1 Do you mean `echo set ubiquity/only-show-installable-languages false | debconf-communicate`?
Yes, it works but the user needs to install the language pack after the OOBE.
Is it acceptable for you?

**Comment by superm1** [comment]
No that's not what I had in mind, but that's good to consider a 4th idea.
What I was thinking was to undo preseed for `debian-installer/locale` or `debian-installer/language` and that should show ubiquity language selection to come up before partitioner comes up.

As you can see dell-bootstrap comes before language https://github.com/dell/dell-recovery/blob/master/ubiquity/dell-bootstrap.py#L49 so if the questions language asks aren't answered it will display the page.

**Comment by fourdollars** [comment]
I see.

**Comment by superm1** [comment]
Yeah I think just add `debian-installer/locale` to https://github.com/dell/dell-recovery/blob/master/ubiquity/dell-bootstrap.py#L525 and you can POC it.

**Comment by superm1** [comment]
(See 0edf734279b41bbdd62822c7c06b76ecdda142d5 for history about how it actually gets set now)

**Comment by fourdollars** [comment]
It stuck after I added `debian-installer/locale` and `debian-installer/language` into the list in the function of unset_drive_preseeds().

**Comment by superm1** [comment]
Stuck as in installed frozen? Or it worked?

**Comment by fourdollars** [comment]
It doesn't work and it stuck after I selected "Customize installation." and clicked the Continue button.

**Comment by superm1** [comment]
Can you check ubiquity verbose log for hint?

**Comment by fourdollars** [comment]
I do some measurement to install all language packs (366 packages) into the /target on some NVMe drive.
It takes about 4m30.
If I keep the zh-hant language pack and remove other language packs (328 packages), it takes about 55 seconds.

**Comment by fourdollars** [comment]
Unset debian-installer/locale and debian-installer/language will cause `AttributeError: 'NoneType' object has no attribute 'replace'` in ubi-language.py.

**Comment by superm1** [comment]
>Unset debian-installer/locale and debian-installer/language will cause AttributeError: 'NoneType' object has no attribute 'replace' in ubi-language.py.

My guess is that this failure comes from this line: https://git.launchpad.net/ubiquity/tree/ubiquity/plugins/ubi-language.py?h=focal#n262 because no language is picked.  So to avoid page being skipped I think just remove seen attribute.

So can you just instead remove the seen attribute from those two specific keys?
```
self.db.fset(key, 'seen', 'false')
```

>I do some measurement to install all language packs (366 packages) into the /target on some NVMe drive.
>It takes about 4m30.
>If I keep the zh-hant language pack and remove other language packs (328 packages), it takes about 55 seconds.

I think that's probably too long, lets see if we can instead work on this way to show language page in this type of install and rule that out first.

**Comment by fourdollars** [comment]
I tried the following change and it still has the same error in ubi-language.py.
```
diff --git a/ubiquity/dell-bootstrap.py b/ubiquity/dell-bootstrap.py
index bb39249..9743edf 100644
--- a/ubiquity/dell-bootstrap.py
+++ b/ubiquity/dell-bootstrap.py
@@ -904,6 +904,8 @@ class Page(Plugin):
             elif rec_type == "interactive":
                 self.ui.show_dialog("forward")
                 self.unset_drive_preseeds()
+                self.db.fset('debian-installer/locale', 'seen', 'false')
+                self.db.fset('debian-installer/language', 'seen', 'false')
 
             # Factory install, and booting from RP
             else:
```

**Comment by fourdollars** [comment]
@superm1 Do you know how to detect the customized installation in the chroot script?
I checked the rec_type in the chroot script but it returns dynamic.

**Comment by superm1** [comment]
>I tried the following change and it still has the same error in ubi-language.py.

Well that's too bad.  I don't really understand what that page is expecting coming in, this is almost sounding like a bug in ubiquity.  It really would be cleanest to just ask language at that time.

> I checked the rec_type in the chroot script but it returns dynamic.

Actually checking `rec_type` is what I was going to suggest, but if you check that the device for `/cdrom` is not the same as `/target` is probably another way to approach it.

**Comment by fourdollars** [comment]
This original issue report doesn't seem to be an issue after using https://paste.ubuntu.com/p/vzZBb2h3fG/.
It also needs a workaround chroot script for ubiquity-dm to raise the privileges.
`sed -i '0,/preexec_fn=self.drop_privileges)/s//preexec_fn=self.regain_privileges)/' /usr/bin/ubiquity-dm`
```
def run_hooks(self, hookdir):
    if os.path.isdir(hookdir):
        # Exclude hooks containing '.', so that *.dpkg-* et al are avoided.
        hooks = [entry for entry in os.listdir(hookdir)
                 if '.' not in entry]
        for hookentry in hooks:
            hook = os.path.join(hookdir, hookentry)
            subprocess.call(
                hook, stdout=logfile, stderr=logfile,
                preexec_fn=self.drop_privileges)
```
